### ISSUE TITLE
Windows build error - Audio.zig

### ISSUE THREAD

**Issue by wilsonk** [zig-community/Zig-Showdown#8]
I pulled and built a new zig compiler on Dec 11, then tried to 'zig build assets install' Zig-Showdown for the first time. I ran into this error late in the build process:

``.\src\client\Audio.zig:139:44: error: expected type '[]const f32', found '[]align(1) f32'``
``      .samples = std.mem.bytesAsSlice(f32, raw_data),``

I temporarily got around this error by changing line 134 of Audio.zig to:

```
 samples: []align(1) f32,
```
Just thought I would mention it here in case others ran into this error.

**Comment by ikskuh** [comment]
Fixed in 4b22112712dc822e119c764bf340bce3a50971db
